/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion.Transporte;
import capaNegocio.Controlador;
import entidades.Transporte;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author Juan magallanes
 */
public class JPReporteTransporte extends javax.swing.JPanel {

    private JTextField txtPlaca;
    private JComboBox<String> cmbTipo;
    private JSpinner spinnerAnio;
    private JComboBox<String> cmbEstado;
    private JButton btnBuscar;
    private JTable tabla;
    private DefaultTableModel modelo;
    /**
     * Creates new form JPReporteTransporte
     */
    public JPReporteTransporte() {
        setLayout(new BorderLayout());

        txtPlaca = new JTextField();
        cmbTipo = new JComboBox<>(new String[]{"", "Bus", "Camioneta", "Camión", "Furgoneta"});
        spinnerAnio = new JSpinner(new SpinnerNumberModel(0, 0, 2050, 1));
        cmbEstado = new JComboBox<>(new String[]{"", "Activo", "Inactivo"});
        btnBuscar = new JButton("Buscar");

        JPanel filtros = new JPanel(new GridLayout(2, 4, 5, 5));
        filtros.setBorder(BorderFactory.createTitledBorder("Filtros de búsqueda"));
        filtros.add(new JLabel("Placa:"));
        filtros.add(txtPlaca);
        filtros.add(new JLabel("Tipo Vehículo:"));
        filtros.add(cmbTipo);
        filtros.add(new JLabel("Año Fabricación:"));
        filtros.add(spinnerAnio);
        filtros.add(new JLabel("Estado:"));
        filtros.add(cmbEstado);

        add(filtros, BorderLayout.NORTH);

        modelo = new DefaultTableModel(new String[]{
            "Placa", "Modelo", "Tipo", "Km", "Año", "Consumo", "Estado"
        }, 0);
        tabla = new JTable(modelo);
        add(new JScrollPane(tabla), BorderLayout.CENTER);
        add(btnBuscar, BorderLayout.SOUTH);

        btnBuscar.addActionListener(e -> {
            String placa = txtPlaca.getText().trim();
            String tipo = (String) cmbTipo.getSelectedItem();
            int anio = (int) spinnerAnio.getValue();
            String estadoStr = (String) cmbEstado.getSelectedItem();
            Boolean estado = null;

            if ("Activo".equals(estadoStr)) estado = true;
            else if ("Inactivo".equals(estadoStr)) estado = false;

            ArrayList<Transporte> lista = Controlador.buscarTransporte(placa, tipo, anio, estado);
            actualizarTabla(lista);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void actualizarTabla(ArrayList<Transporte> lista) {
        modelo.setRowCount(0);
        for (Transporte t : lista) {
            modelo.addRow(new Object[]{
                t.getPlaca(), t.getModeloVehiculo(), t.getTipoVehiculo(), t.getKilometraje(),
                t.getAnioFabricacion(), t.getConsumoCombustiblePorKm(),
                t.isEstado() ? "Activo" : "Inactivo"
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
