/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaPresentacion.Cliente.JPCliente;
import capaPresentacion.Factura.JPFactura;
import capaPresentacion.PaquetesTuristicos.JPCreatePaquete;
import capaPresentacion.PaquetesTuristicos.JPPaquete;
import capaPresentacion.Reserva.JPReserva;
import capaPresentacion.Transporte.JPTransporte;
import capaPresentacion.Usuario.JPUsuario;

/**
 *
 * @author Juan magallanes
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        initTabs();
    }
    JPUsuario panelUsuario = new JPUsuario();
    JPCliente panelCliente = new JPCliente();
    JPTransporte panelTransporte = new JPTransporte();
    JPPaquete panelPaquete = new JPPaquete();
    JPReserva panelReserva = new JPReserva();
    JPFactura panelFactura = new JPFactura();
    
    // Después de initComponents()
    private void initTabs() {
        
        panelModulos.addTab("Usuario", panelUsuario);
        panelModulos.addTab("Cliente", panelCliente);
        panelModulos.addTab("Transporte", panelTransporte);
        panelModulos.addTab("Paquete Turistico", panelPaquete);
        panelModulos.addTab("Reserva", panelReserva);
        panelModulos.addTab("Factura", panelFactura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModulos = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelModulos.setToolTipText("");
        panelModulos.setMinimumSize(new java.awt.Dimension(612, 439));
        panelModulos.setPreferredSize(new java.awt.Dimension(612, 475));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelModulos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane panelModulos;
    // End of variables declaration//GEN-END:variables
}
