/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion.Cliente;

import capaNegocio.Controlador;
import entidades.Cliente;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * @author Juan magallanes
 */
public class JPReporteCliente extends javax.swing.JPanel {
       private JTextField txtNombre, txtCedula;
       private JSpinner spinnerDesde, spinnerHasta;
       private JButton btnBuscar;
       private JTable tablaClientes;
       private DefaultTableModel modelo;
    /**
     * Creates new form JPReporteCliente
     */
    public JPReporteCliente() {
        setLayout(new BorderLayout());

        // Campos de filtro
        txtNombre = new JTextField();
        txtCedula = new JTextField();
        spinnerDesde = new JSpinner(new SpinnerDateModel());
        spinnerHasta = new JSpinner(new SpinnerDateModel());

        spinnerDesde.setEditor(new JSpinner.DateEditor(spinnerDesde, "yyyy-MM-dd"));
        spinnerHasta.setEditor(new JSpinner.DateEditor(spinnerHasta, "yyyy-MM-dd"));

        btnBuscar = new JButton("Buscar");

        JPanel panelFiltro = new JPanel(new GridLayout(3, 2, 5, 5));
        panelFiltro.setBorder(BorderFactory.createTitledBorder("Filtros de búsqueda"));

        panelFiltro.add(new JLabel("Nombre:"));
        panelFiltro.add(txtNombre);
        panelFiltro.add(new JLabel("Cédula:"));
        panelFiltro.add(txtCedula);
        panelFiltro.add(new JLabel("Fecha desde:"));
        panelFiltro.add(spinnerDesde);
        panelFiltro.add(new JLabel("Fecha hasta:"));
        panelFiltro.add(spinnerHasta);

        add(panelFiltro, BorderLayout.NORTH);

        modelo = new DefaultTableModel(new String[]{"ID", "Nombre", "Correo", "Dirección", "Teléfono", "Cédula", "Fecha Registro"}, 0);
        tablaClientes = new JTable(modelo);
        add(new JScrollPane(tablaClientes), BorderLayout.CENTER);

        add(btnBuscar, BorderLayout.SOUTH);

        // Acción del botón
        btnBuscar.addActionListener(e -> {
            Timestamp desde = new Timestamp(((Date) spinnerDesde.getValue()).getTime()) {};
            Timestamp hasta = new Timestamp(((Date) spinnerHasta.getValue()).getTime());

            ArrayList<Cliente> resultados = Controlador.buscarClientes(
                txtNombre.getText(), txtCedula.getText(), desde, hasta);
            actualizarTabla(resultados);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 private void actualizarTabla(ArrayList<Cliente> lista) {
        modelo.setRowCount(0); // limpiar
        for (Cliente c : lista) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNombreCompleto(),
                c.getCorreoElectronico(),
                c.getDireccion(),
                c.getTelefono(),
                c.getCedula(),
                c.getFechaRegistro()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
