/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion.PaquetesTuristicos;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import entidades.PaqueteTuristico;
import capaNegocio.Controlador;
/**
 *
 * @author Juan magallanes
 */
public class JPReportePaquete extends javax.swing.JPanel {

    private JComboBox<String> cmbDestino, cmbHospedaje;
    private JTextField txtTransporte;
    private JSpinner spinFechaInicio, spinFechaFin, spinDuracionMin;
    private JButton btnBuscar;
    private JTable tblPaquetes;
    private DefaultTableModel modeloTabla;
    private Controlador controlador = new Controlador();
    /**
     * Creates new form JPReportePaquete
     */
    public JPReportePaquete() {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        // Panel de filtros
        JPanel panelFiltros = new JPanel(new GridLayout(3, 4, 10, 10));
        panelFiltros.setBorder(BorderFactory.createTitledBorder("Filtros de búsqueda"));

        // Filtros
        cmbDestino = new JComboBox<>(new String[]{"Todos", "Perú", "México", "Ecuador"});
        cmbHospedaje = new JComboBox<>(new String[]{"Todos", "Hotel 3 estrellas", "Hotel 5 estrellas", "Hostal", "Cabaña", "Resort"});
        txtTransporte = new JTextField();

        spinFechaInicio = new JSpinner(new SpinnerDateModel());
        spinFechaInicio.setEditor(new JSpinner.DateEditor(spinFechaInicio, "yyyy-MM-dd"));
        spinFechaFin = new JSpinner(new SpinnerDateModel());
        spinFechaFin.setEditor(new JSpinner.DateEditor(spinFechaFin, "yyyy-MM-dd"));

        spinDuracionMin = new JSpinner(new SpinnerNumberModel(0, 0, 30, 1));

        // Agregar filtros
        panelFiltros.add(new JLabel("Destino:"));
        panelFiltros.add(cmbDestino);
        panelFiltros.add(new JLabel("Hospedaje:"));
        panelFiltros.add(cmbHospedaje);
        panelFiltros.add(new JLabel("Transporte (placa):"));
        panelFiltros.add(txtTransporte);
        panelFiltros.add(new JLabel("Fecha Inicio:"));
        panelFiltros.add(spinFechaInicio);
        panelFiltros.add(new JLabel("Fecha Fin:"));
        panelFiltros.add(spinFechaFin);
        panelFiltros.add(new JLabel("Duración mínima (días):"));
        panelFiltros.add(spinDuracionMin);

        // Botón de búsqueda
        JPanel panelBoton = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btnBuscar = new JButton("Buscar");
        panelBoton.add(btnBuscar);

        // Tabla
        modeloTabla = new DefaultTableModel(new String[]{
            "Nombre", "Destino", "Precio Destino", "Hospedaje", "Transporte", "Actividades", "Duración", "Fecha Inicio", "Fecha Fin", "Precio Total"
        }, 0);
        tblPaquetes = new JTable(modeloTabla);
        JScrollPane scrollTabla = new JScrollPane(tblPaquetes);
        scrollTabla.setBorder(BorderFactory.createTitledBorder("Reporte de Paquetes Turísticos"));

        // Agregar componentes al panel principal
        add(panelFiltros);
        add(panelBoton);
        add(scrollTabla);

        // Evento
        btnBuscar.addActionListener(e -> buscarPaquetes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void buscarPaquetes() {
    String destino = cmbDestino.getSelectedItem().toString();
    String hospedaje = cmbHospedaje.getSelectedItem().toString();
    String transporte = txtTransporte.getText().trim();
    int duracionMin = (int) spinDuracionMin.getValue();

    // Convertir fechas a String
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format((Date) spinFechaInicio.getValue());
    String fechaFinStr = sdf.format((Date) spinFechaFin.getValue());

    // Llamar al controlador con strings
    ArrayList<PaqueteTuristico> lista = controlador.obtenerPaquetesFiltrados(
        destino.equals("Todos") ? null : destino,
        hospedaje.equals("Todos") ? null : hospedaje,
        transporte.isEmpty() ? null : transporte,
        fechaInicioStr,
        fechaFinStr,
        duracionMin
    );

    // Limpiar y llenar tabla
    modeloTabla.setRowCount(0);
    for (PaqueteTuristico p : lista) {
        modeloTabla.addRow(new Object[]{
            p.getNombrePaquete(),
            p.getDestino(),
            p.getPrecioDestino(),
            p.getHospedaje(),
            p.getTransportePlaca(),
            p.getActividades(),
            p.getDuracionDias(),
            p.getFechaInicio(),
            p.getFechaFin(),
            p.getPrecioTotal()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
