/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion.Factura;

import capaNegocio.Controlador;
import entidades.Factura;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan magallanes
 */
public class JPReporteFactura extends javax.swing.JPanel {

 private JSpinner spinFechaInicio, spinFechaFin;
    private JComboBox<String> cmbEstado, cmbMetodoPago;
    private JButton btnBuscar;
    private JTable tblReporteFactura;
    private DefaultTableModel modeloTabla;
    private Controlador controlador = new Controlador();
    
    /**
     * Creates new form JPReporteFactura
     */
    public JPReporteFactura() {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        // Panel de filtros
        JPanel panelFiltros = new JPanel(new GridLayout(2, 4, 10, 10));
        panelFiltros.setBorder(BorderFactory.createTitledBorder("Filtros"));

        // Fechas
        spinFechaInicio = new JSpinner(new SpinnerDateModel());
        spinFechaInicio.setEditor(new JSpinner.DateEditor(spinFechaInicio, "yyyy-MM-dd"));
        spinFechaFin = new JSpinner(new SpinnerDateModel());
        spinFechaFin.setEditor(new JSpinner.DateEditor(spinFechaFin, "yyyy-MM-dd"));

        // Estado y método de pago
        cmbEstado = new JComboBox<>(new String[]{"Todos", "Emitida", "Pagada", "Pendiente", "ANULADO"});
        cmbMetodoPago = new JComboBox<>(new String[]{"Todos", "Efectivo", "Tarjeta de Crédito", "Transferencia"});

        panelFiltros.add(new JLabel("Fecha Inicio:"));
        panelFiltros.add(spinFechaInicio);
        panelFiltros.add(new JLabel("Fecha Fin:"));
        panelFiltros.add(spinFechaFin);
        panelFiltros.add(new JLabel("Estado:"));
        panelFiltros.add(cmbEstado);
        panelFiltros.add(new JLabel("Método Pago:"));
        panelFiltros.add(cmbMetodoPago);

        // Botón de búsqueda
        JPanel panelBoton = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btnBuscar = new JButton("Buscar");
        btnBuscar.addActionListener(e -> buscarFacturas());
        panelBoton.add(btnBuscar);

        // Tabla
        modeloTabla = new DefaultTableModel(new String[]{
            "ID", "Reserva ID", "Fecha Emisión", "Método Pago", "Subtotal", "IVA", "Total", "Estado"
        }, 0);
        tblReporteFactura = new JTable(modeloTabla);
        JScrollPane scroll = new JScrollPane(tblReporteFactura);
        scroll.setBorder(BorderFactory.createTitledBorder("Reporte de Facturas"));

        // Agregar todo al panel principal
        add(panelFiltros);
        add(panelBoton);
        add(scroll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void buscarFacturas() {
        Date fechaInicio = (Date) spinFechaInicio.getValue();
        Date fechaFin = (Date) spinFechaFin.getValue();
        String estado = cmbEstado.getSelectedItem().toString();
        String metodoPago = cmbMetodoPago.getSelectedItem().toString();

        ArrayList<Factura> lista = controlador.obtenerFacturasReporte(fechaInicio, fechaFin, estado, metodoPago);

        modeloTabla.setRowCount(0);
        for (Factura f : lista) {
            modeloTabla.addRow(new Object[]{
                f.getId(),
                f.getReserva_id(),
                f.getFecha_emision(),
                f.getMetodo(),
                f.getSubTotal(),
                f.getIva(),
                f.getTotal(),
                f.getEstado()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
