/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacion.Usuario;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import capaNegocio.Controlador;
import entidades.Usuario;
import java.awt.*;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
/**
 *
 * @author Juan magallanes
 */
public class JPReporteUsuario extends javax.swing.JPanel {
private JTextField txtCedula, txtNombre;
    private JComboBox<String> cmbRol, cmbEstado;
    private JSpinner spDesde, spHasta;
    private JButton btnBuscar;
    private JTable tblUsuarios;
    /**
     * Creates new form JPReporteUsuario
     */
    public JPReporteUsuario() {
        setLayout(new BorderLayout());

        // Panel de filtros
        JPanel pnlFiltros = new JPanel(new GridLayout(3, 4, 10, 10));

        txtCedula = new JTextField();
        txtNombre = new JTextField();
        cmbRol = new JComboBox<>(new String[]{"Todos", "Administrador", "Vendedor"});
        cmbEstado = new JComboBox<>(new String[]{"Todos", "Activo", "Inactivo"});

        spDesde = new JSpinner(new SpinnerDateModel());
        spDesde.setEditor(new JSpinner.DateEditor(spDesde, "yyyy-MM-dd"));
        spHasta = new JSpinner(new SpinnerDateModel());
        spHasta.setEditor(new JSpinner.DateEditor(spHasta, "yyyy-MM-dd"));

        btnBuscar = new JButton("Buscar");

        pnlFiltros.add(new JLabel("Cédula:"));
        pnlFiltros.add(txtCedula);
        pnlFiltros.add(new JLabel("Nombre completo:"));
        pnlFiltros.add(txtNombre);

        pnlFiltros.add(new JLabel("Rol:"));
        pnlFiltros.add(cmbRol);
        pnlFiltros.add(new JLabel("Estado:"));
        pnlFiltros.add(cmbEstado);

        pnlFiltros.add(new JLabel("Desde:"));
        pnlFiltros.add(spDesde);
        pnlFiltros.add(new JLabel("Hasta:"));
        pnlFiltros.add(spHasta);

        add(pnlFiltros, BorderLayout.NORTH);

        // Tabla
        tblUsuarios = new JTable();
        tblUsuarios.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Cédula", "Nombre", "Correo", "Teléfono", "Dirección", "Rol", "Usuario", "Fecha Registro", "Estado"}
        ));

        JScrollPane scroll = new JScrollPane(tblUsuarios);
        add(scroll, BorderLayout.CENTER);

        // Botón
        JPanel pnlBoton = new JPanel();
        pnlBoton.add(btnBuscar);
        add(pnlBoton, BorderLayout.SOUTH);

        btnBuscar.addActionListener(e -> cargarReporteUsuarios());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void cargarReporteUsuarios() {
        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();
        String rol = (String) cmbRol.getSelectedItem();
        String estado = (String) cmbEstado.getSelectedItem();

        Timestamp desde = null;
        Timestamp hasta = null;

        if (spDesde.getValue() != null) {
            desde = new Timestamp(((Date) spDesde.getValue()).getTime());
        }
        if (spHasta.getValue() != null) {
            hasta = new Timestamp(((Date) spHasta.getValue()).getTime());
        }

        Controlador controlador = new Controlador();
        List<Usuario> lista = controlador.buscarUsuariosReporte(cedula, nombre, rol, estado, desde, hasta);

        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0);

        for (Usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getId(), u.getCedula(), u.getNombreCompleto(), u.getCorreoElectronico(),
                u.getTelefono(), u.getDireccion(), u.getRol(), u.getNombreUsuario(),
                u.getFechaRegistro(), u.getEstado()
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
